### ISSUE TITLE
Circuitry.flush can halt or crash application

### ISSUE THREAD

**Issue by mhuggins** [kapost/circuitry#11]
The problem comes down to the user's `to_json` implementation for the object being serialized.  If it recurses, has an infinite loop, etc., then flushing will never return.  I propose fixing this by adding a `timeout` option that can also be defined in `Circuitry.config`.  If the timeout is reached, the user-defined `error_handler` block should be processed, and processing should resume.

**Comment by brandonc** [comment]
:+1:
