### ISSUE TITLE
Prevent duplicate message processing

### ISSUE THREAD

**Issue by mhuggins** [kapost/circuitry#12]
After publishing the blog post about circuitry, it was pointed out to me that with SQS, it is possible to receive a message more than once.  Specifically [from the FAQ](http://aws.amazon.com/sqs/faqs/):

> **Q: How many times will I receive each message?**
>
> Amazon SQS is engineered to provide “at least once” delivery of all messages in its queues. Although most of the time each message will be delivered to your application exactly once, you should design your system so that processing a message more than once does not create any errors or inconsistencies.

With that in mind, we'll need to implement some sort of locking strategy.  I'm thinking that as soon as a message is received, the gem should store a soft "processing" lock for the message handle ID with a reasonable timeout (configurable by the application, e.g.: 15 minutes) that changes to a hard "processed" lock once it successfully completes.  We could offer out of the box locking strategies (e.g.: memcached, redis, DB, etc.) with an option to roll your own as well.  For comparison, I once tried to do something similar for the [redis-store gem](https://github.com/redis-store/redis-store/pull/145) that I think would be suitable here.

/cc @brandonc

**Comment by skwp** [comment]
I would also recommend providing a no-op locking strategy or an option to turn it off in case performance was more important than uniqueness gathering.

**Comment by mhuggins** [comment]
@skwp This has been fixed by #13, and a no-op strategy made it into the gem as well.  This has all been released as v1.2.0 if you're interested in the feature.  Take a look at the [configuration options](https://github.com/kapost/circuitry#usage) and [lock strategies](https://github.com/kapost/circuitry#lock-strategies) for more insight. :)

**Comment by skwp** [comment]
Awesome I just realized after I commented. We are just exploring the possibility of using sqs/sns. Nice job on the gem.

**Comment by mhuggins** [comment]
Thanks!  Please let me know if you have any questions or hit any speed bumps with using the gem! :)
