### ISSUE TITLE
Pool limits?

### ISSUE THREAD

**Issue by waynerobinson** [kapost/circuitry#23]
Are there limits on the size of the child (fork or thread) pool? Or could a Circuitry subscriber drain and entire SQS queue to itself even though it doesn't have the capacity to process the jobs in a reasonable time?

**Comment by mhuggins** [comment]
Hi @waynerobinson, I think what you're looking for is the `batch_size` option on the subscriber.  The default value is 10.

**Comment by waynerobinson** [comment]
Isn't this just how many messages are retrieved per request? Does it fork and process all of these messages before moving on and requesting another batch of messages? Does this mean we're limited to the maximum SQS batch size of 10 (which is also per-batch size limited to 256KB) as the pool size?

**Comment by mhuggins** [comment]
Yes, this is the number of messages received per request, and each of those messages is process before fetching another batch.  There is no pooling implemented beyond that at the moment.  If you have suggestions or would like to submit a PR implementing it, please feel free!

**Comment by mhuggins** [comment]
Alternatively, pooling could just happen at the application level or with a generic pooling gem.

**Comment by mhuggins** [comment]
I haven't heard back on this in awhile, so I'm going to close it. Please reopen if you'd like to continue the discussion.
