### ISSUE TITLE
Middleware for publisher & subscriber

### ISSUE THREAD

**Issue by mhuggins** [kapost/circuitry#31]
As I was looking into adding monitoring for messages being published & received, I thought it would be a nice feature if this could be hooked in via middleware.

For Kapost, this would make it easy to create a gem that we could share across our apps for tracking to DataDog (via [seismograph](https://github.com/kapost/seismograph)).

Imagine something like the following:

**Middleware:**

```ruby
class Circuitry::Middleware::Seismograph
  attr_reader :namespace

  def initialize(options = {})
    @namespace = options.fetch(:namespace)
  end

  def call(topic, message, &callback)
    tags = ["topic:#{topic}"]

    sensor.benchmark(namespace, tags: tags) do
      callback.call(topic, message)
    end
  end

  private

  def sensor
    @sensor ||= Seismograph::Sensor.new('circuitry')
  end
end
```

**Configuration:**

```ruby
Circuitry.configure do |config|
  config.publish_middleware do |m|
    m.add Circuitry::Middleware::Seismograph, namespace: 'publisher'
  end

  config.subscribe_middleware do |m|
    m.add Circuitry::Middleware::Seismograph, namespace: 'subscriber'
  end
end
```

Middleware should respond to standard methods utilized by rack middleware, [sidekiq middleware](https://github.com/mperham/sidekiq/blob/master/lib/sidekiq/middleware/chain.rb), etc., including:

* add
* remove
* prepend
* insert_before
* insert_after

**Comment by brandonc** [comment]
#33 ✅
