### ISSUE TITLE
Testing

### ISSUE THREAD

**Issue by diego1686** [kapost/circuitry#63]
Hi! Could you give an example of how to check if a message was published from rspec?

For example, I have an after_save callback on some model and I want to check that a message with some information about that update was published to some topic. How can I do that? Thanks!

**Comment by mhuggins** [comment]
You should be able to do something as simple as:

```ruby
expect(Circuitry).to have_received(:publish).with(topic, data)
```

Alternatively, if you're using an `Circuitry::Publisher` instance, you can do something like:

```ruby
let(:publisher) { double("Circuitry::Publisher", publish: true) }

before do
  allow(Circuitry::Publisher).to receive(:new).and_return(publisher)
end

it "publishes" do
  expect(publisher).to have_received(:publish).with(topic, data)
end
```

**Comment by diego1686** [comment]
Thanks @mhuggins 

Using the first option I got this:

`Circuitry expected to have received publish, but that object is not a spy or method has not been stubbed.`

I'm publishing in this way:

`Circuitry.publish("topic", object.to_json)`

**Comment by mhuggins** [comment]
Ahh, yeah, that's an expectation of how RSpec works.  If you want to use `have_received`, you need to stub that method first, i.e.:

```ruby
allow(Circuitry).to receive(:publish)
```

Alternatively, you can avoid stubbing by declaring your expectation *before* running your test:

```ruby
expect(publisher).to receive(:publish).with(topic, data)
```

**Comment by diego1686** [comment]
Great, thanks @mhuggins!!

**Comment by mhuggins** [comment]
No problem.  I'm going to close this, but feel free to ping me again if it's not working!
