### ISSUE TITLE
Error when RAILS_ENV=test rake db:reset

### ISSUE THREAD

**Issue by diego1686** [kapost/circuitry#64]
After I run rake db:reset, I got this:

```
...
...
-- add_index("users", ["email"], {:name=>"index_users_on_email", :unique=>true, :using=>:btree})
   -> 0.0237s
-- add_index("users", ["reset_password_token"], {:name=>"index_users_on_reset_password_token", :unique=>true, :using=>:btree})
   -> 0.0281s
-- initialize_schema_migrations_table()
   -> 0.0308s
I, [2016-11-17T15:18:50.687102 #27701]  INFO -- : Publishing message to test-User-created
rake aborted!
Aws::SNS::Errors::InvalidClientTokenId: The security token included in the request is invalid.
```

When I run the tests with rspec everything works well!

**Comment by mhuggins** [comment]
Do you have an after_create hook on a users model that is trying to publish a circuitry message?  That's all I can guess from the info you provided.

Also, do you already have `requite 'circuitry/testing'` in your rspec config?

**Comment by diego1686** [comment]
@mhuggins Yes, I have a hook. And I have the require also. When I run the tests using the rspec command, it works well. But when I try to reset the database, It raises that exception. I don't know why, the environment is test in both cases. The rake db:reset is executed by Jenkins before it runs the tests

**Comment by mhuggins** [comment]
Yeah, that was my concern.  If you're just running something in test env without rspec, then circuitry/testing won't be used.  Perhaps what you could do is update your `config/initializers/circuitry.rb` file to include this:

```ruby
require 'circuitry/testing' if Rails.env.test?
```

**Comment by diego1686** [comment]
@mhuggins It did the trick! Thanks

**Comment by mhuggins** [comment]
No problem!  Glad I could help. :)
